export default class Act {

  static TOGGLE_LEFT_NAV = 'TOGGLE_LEFT_NAV'
  static TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE'

  static ENTER_MATCH = 'ENTER_MATCH'
  static EXIT_MATCH = 'EXIT_MATCH'

  static AUTH_REQUIRED = 'AUTH_REQUIRED'

  static LOGIN_USER_REQUESTED = 'LOGIN_USER_REQUESTED'
  static LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
  static LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

  static SIGNUP_USER_START = 'SIGNUP_USER_START'
  static SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS'
  static SIGNUP_USER_ERROR = 'SIGNUP_USER_ERROR'

  static LOGOUT_USER_REQUESTED = 'LOGOUT_USER_REQUESTED'
  static LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'
  static LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR'

  static FLASH_MESSAGE_START = 'FLASH_MESSAGE_START'
  static FLASH_MESSAGE_END = 'FLASH_MESSAGE_END'

}
