export default class FKAct {

  static FK_LIST_REQUESTED = 'FK_LIST_REQUESTED'
  static FK_LIST_SUCCESS = 'FK_LIST_SUCCESS'
  static FK_LIST_ERROR = 'FK_LIST_ERROR'

  static FK_READ_REQUESTED = 'FK_READ_REQUESTED'
  static FK_READ_SUCCESS = 'FK_READ_SUCCESS'
  static FK_READ_ERROR = 'FK_READ_ERROR'

  static FK_CLEAR_SELECTION = 'FK_CLEAR_SELECTION'
  static FK_PRELOAD_RECORD = 'FK_PRELOAD_RECORD'
  static FK_RESET = 'FK_RESET'

  static FK_LAST_SEARCH_TEXT = 'FK_LAST_SEARCH_TEXT'
}
